/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulas;

import PVT.Clasificacion_Fluidos;
import java.awt.Font;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author EQUIPO
 */
public class Porosity extends javax.swing.JDialog {
    
    Clasificacion_Fluidos cf = new Clasificacion_Fluidos();

    /**
     * Creates new form Porosity
     */
    public Porosity(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/PorComunication.txt");
        textoPorComun(is);
        InputStream is2 = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/WherePorosity.txt");
        textoWhere(is2);

        grupoBotonesTypePorosity.add(effectivePorRB);
        grupoBotonesTypePorosity.add(ineffectivePorRB);
        grupoBotonesTypePorosity.add(absolutePorRB);

        grupoBotonesTypePorosity.add(primaryPorRB);
        grupoBotonesTypePorosity.add(secundaryPorRB);
        
        DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
        JTableHeader th;
        th = jTableQualityPorosity.getTableHeader();
        Font fuente = new Font("Verdana", Font.BOLD, 12);
        th.setFont(fuente);
        Alinear.setHorizontalAlignment(SwingConstants.CENTER);//.LEFT .RIGHT .CENTER
        jTableQualityPorosity.getColumnModel().getColumn(0).setCellRenderer(Alinear);
        jTableQualityPorosity.getColumnModel().getColumn(1).setCellRenderer(Alinear);
        
        JTableHeader th2;
        th2 = jTableExample.getTableHeader();
        th2.setFont(fuente);
        jTableExample.getColumnModel().getColumn(0).setCellRenderer(Alinear);
        jTableExample.getColumnModel().getColumn(1).setCellRenderer(Alinear);
        jTableExample.getColumnModel().getColumn(2).setCellRenderer(Alinear);
        jTableExample.getColumnModel().getColumn(3).setCellRenderer(Alinear);
        
        pintarImagen(AvePor1, "/Images/formulas/AveragePorosity1.jpg");
        pintarImagen(AvePor2, "/Images/formulas/AveragePorosity2.jpg");
        pintarImagen(ThikPor1, "/Images/formulas/PorosityBythickness1.jpg");
        pintarImagen(ThikPor2, "/Images/formulas/PorosityBythickness2.jpg");
        pintarImagen(AreaPor1, "/Images/formulas/PorosityByArea1.jpg");
        pintarImagen(AreaPor2, "/Images/formulas/PorosityByArea2.jpg");
        pintarImagen(VolPor1, "/Images/formulas/PorosityByVolume1.jpg");
        pintarImagen(VolPor2, "/Images/formulas/PorosityByVolume2.jpg");
        pintarImagen(jLabelVolTotal, "/Images/formulas/VolumenTotal.jpg");
        pintarImagen(jLabelVolGranos, "/Images/formulas/VolumenGranos.jpg");
        pintarImagen(jLabelVolPoro3, "/Images/formulas/VolumenPoro3.jpg");
        pintarImagen(jLabelVolPoro4, "/Images/formulas/VolumenPoro4.jpg");
        pintarImagen(jLabelVolPoro5, "/Images/formulas/VolumenPoro5.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesTypePorosity = new javax.swing.ButtonGroup();
        grupoBotonesOriAndTime = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaPorComunication = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaPor = new javax.swing.JTextArea();
        effectivePorRB = new javax.swing.JRadioButton();
        absolutePorRB = new javax.swing.JRadioButton();
        ineffectivePorRB = new javax.swing.JRadioButton();
        showTypePorosity = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        primaryPorRB = new javax.swing.JRadioButton();
        secundaryPorRB = new javax.swing.JRadioButton();
        showOriAndTimePor = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaPorOri = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQualityPorosity = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaPorWhere = new javax.swing.JTextArea();
        jLabelVolTotal = new javax.swing.JLabel();
        jLabelVolGranos = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabelVolPoro3 = new javax.swing.JLabel();
        jLabelVolPoro4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelVolPoro5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AvePor1 = new javax.swing.JLabel();
        AvePor2 = new javax.swing.JLabel();
        ThikPor1 = new javax.swing.JLabel();
        ThikPor2 = new javax.swing.JLabel();
        AreaPor1 = new javax.swing.JLabel();
        VolPor1 = new javax.swing.JLabel();
        VolPor2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExample = new javax.swing.JTable();
        AreaPor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Porosity");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Porosity Types"));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("According to Pore Communication"));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaPorComunication.setEditable(false);
        jTextAreaPorComunication.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaPorComunication.setColumns(20);
        jTextAreaPorComunication.setLineWrap(true);
        jTextAreaPorComunication.setRows(5);
        jTextAreaPorComunication.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextAreaPorComunication);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaPor.setEditable(false);
        jTextAreaPor.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaPor.setColumns(20);
        jTextAreaPor.setLineWrap(true);
        jTextAreaPor.setRows(5);
        jTextAreaPor.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextAreaPor);

        effectivePorRB.setBackground(new java.awt.Color(255, 255, 255));
        effectivePorRB.setText("Effective porosity");

        absolutePorRB.setBackground(new java.awt.Color(255, 255, 255));
        absolutePorRB.setText("Absolute porosity");

        ineffectivePorRB.setBackground(new java.awt.Color(255, 255, 255));
        ineffectivePorRB.setText("Ineffective porosity");

        showTypePorosity.setText("Show");
        showTypePorosity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showTypePorosityMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(absolutePorRB)
                            .addComponent(effectivePorRB)
                            .addComponent(ineffectivePorRB)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(showTypePorosity)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(effectivePorRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ineffectivePorRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(absolutePorRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTypePorosity))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("According to Origin and Time of Deposition"));

        primaryPorRB.setBackground(new java.awt.Color(255, 255, 255));
        primaryPorRB.setText("Primary porosity");

        secundaryPorRB.setBackground(new java.awt.Color(255, 255, 255));
        secundaryPorRB.setText("Secundary porosity");

        showOriAndTimePor.setText("Show");
        showOriAndTimePor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showOriAndTimePorMouseClicked(evt);
            }
        });

        jTextAreaPorOri.setEditable(false);
        jTextAreaPorOri.setColumns(20);
        jTextAreaPorOri.setLineWrap(true);
        jTextAreaPorOri.setRows(5);
        jTextAreaPorOri.setWrapStyleWord(true);
        jScrollPane9.setViewportView(jTextAreaPorOri);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryPorRB)
                            .addComponent(secundaryPorRB)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(showOriAndTimePor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(primaryPorRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secundaryPorRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showOriAndTimePor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableQualityPorosity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Very good", "> 20"},
                {"Good", "15 - 20"},
                {"Regular", "10 - 15"},
                {"Poor", "5 - 10"},
                {"Very poor", "< 5"}
            },
            new String [] {
                "Rock quality", "Porosity (%)"
            }
        ));
        jScrollPane1.setViewportView(jTableQualityPorosity);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Where do these porosity values arise from and why?"));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaPorWhere.setEditable(false);
        jTextAreaPorWhere.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaPorWhere.setColumns(20);
        jTextAreaPorWhere.setLineWrap(true);
        jTextAreaPorWhere.setRows(5);
        jTextAreaPorWhere.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextAreaPorWhere);

        jScrollPane10.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("- We determine the total volume (Vt). Defined by the volume of a cube:\n\n- And then we determine the volume of the grains (Vg) of the rock represented by the volume of a sphere, assuming that the grains are perfectly spherical:");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Step One - Two"));
        jScrollPane10.setViewportView(jTextArea2);

        jScrollPane11.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("We determine the total volume (Vt). Defined by the volume of a cube:\n\nAnd then we determine the volume of the grains (Vg) of the rock represented by the volume of a sphere, assuming that the grains are perfectly spherical:");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("Step Three- Four"));
        jScrollPane11.setViewportView(jTextArea3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabelVolPoro5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelVolPoro5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10)
            .addComponent(jScrollPane11)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabelVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabelVolGranos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabelVolPoro3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelVolPoro4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane8))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVolTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabelVolGranos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVolPoro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVolPoro4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Example:");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Given the following field information, calculate:\n- Mean porosity.\n- Weighted average porosity\n    - By thickness\n    - By area\n    - By volume\n- Determine its quality");
        jScrollPane3.setViewportView(jTextArea1);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTableExample.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "30", "40", "300"},
                {"2", "15", "30", "150"},
                {"3", "25", "20", "250"},
                {"4", "20", "35", "200"},
                {"5", "40", "25", "400"},
                {"6", "15", "20", "150"}
            },
            new String [] {
                "Layers", "Thickness (ft)", "Porosity (%)", "Area (ft2)"
            }
        ));
        jScrollPane2.setViewportView(jTableExample);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(VolPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(AvePor1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(ThikPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(AreaPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AvePor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ThikPor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(AreaPor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VolPor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvePor1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvePor2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThikPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThikPor2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AreaPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AreaPor2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolPor1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolPor2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTypePorosityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTypePorosityMouseClicked
        if (effectivePorRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/EffectivePor.txt");
            textoPor(is);

        } else if (ineffectivePorRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/IneffectivePor.txt");
            textoPor(is);

        } else if (absolutePorRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/AbsolutePor.txt");
            textoPor(is);
        } else {
            JOptionPane.showMessageDialog(this, "You must check at least one option.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_showTypePorosityMouseClicked

    private void showOriAndTimePorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showOriAndTimePorMouseClicked
        if (primaryPorRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/PrimaryPorosity.txt");
            textoPorOriTimeRB(is);
        } else if (secundaryPorRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/SecundaryPorosity.txt");
            textoPorOriTimeRB(is);
        } else {
            JOptionPane.showMessageDialog(this, "You must check at least one option.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_showOriAndTimePorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Porosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Porosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Porosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Porosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Porosity dialog = new Porosity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void textoPor(InputStream is) {
        jTextAreaPor.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaPor.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void textoPorComun(InputStream is) {
        jTextAreaPorComunication.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaPorComunication.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void textoWhere(InputStream is) {
        jTextAreaPorWhere.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaPorWhere.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void textoPorOriTimeRB(InputStream is) {
        jTextAreaPorOri.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaPorOri.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void pintarImagen(JLabel lbl, String ruta) {
        lbl.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(
                lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT)));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaPor1;
    private javax.swing.JLabel AreaPor2;
    private javax.swing.JLabel AvePor1;
    private javax.swing.JLabel AvePor2;
    private javax.swing.JLabel ThikPor1;
    private javax.swing.JLabel ThikPor2;
    private javax.swing.JLabel VolPor1;
    private javax.swing.JLabel VolPor2;
    private javax.swing.JRadioButton absolutePorRB;
    private javax.swing.JRadioButton effectivePorRB;
    private javax.swing.ButtonGroup grupoBotonesOriAndTime;
    private javax.swing.ButtonGroup grupoBotonesTypePorosity;
    private javax.swing.JRadioButton ineffectivePorRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVolGranos;
    private javax.swing.JLabel jLabelVolPoro3;
    private javax.swing.JLabel jLabelVolPoro4;
    private javax.swing.JLabel jLabelVolPoro5;
    private javax.swing.JLabel jLabelVolTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableExample;
    private javax.swing.JTable jTableQualityPorosity;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextAreaPor;
    private javax.swing.JTextArea jTextAreaPorComunication;
    private javax.swing.JTextArea jTextAreaPorOri;
    private javax.swing.JTextArea jTextAreaPorWhere;
    private javax.swing.JRadioButton primaryPorRB;
    private javax.swing.JRadioButton secundaryPorRB;
    private javax.swing.JButton showOriAndTimePor;
    private javax.swing.JButton showTypePorosity;
    // End of variables declaration//GEN-END:variables
}
