/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulas;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO
 */
public class Viscosity extends javax.swing.JDialog {

    /**
     * Creates new form Viscosity
     */
    public Viscosity(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        InputStream is2 = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/Viscosity3.txt");
        textoViscosity2(is2);
        
        buttonGroupViscosity1.add(pressureViscoRB);
        buttonGroupViscosity1.add(tempViscoRB);
        buttonGroupViscosity1.add(densityViscoRB);
        
        buttonGroupViscoOil.add(RBDeadOil);
        buttonGroupViscoOil.add(RBSatuOil);
        buttonGroupViscoOil.add(RBSubSatOil);
        
        buttonGroupViscoTypes.add(RBApparentViscosity);
        buttonGroupViscoTypes.add(RBEnglerViscosity);
        buttonGroupViscoTypes.add(RBFurolSayboltViscosity);
        buttonGroupViscoTypes.add(RBKinematicViscosity);
        buttonGroupViscoTypes.add(RBRedwoodViscosity);
        buttonGroupViscoTypes.add(RBRelativeViscosity);
        buttonGroupViscoTypes.add(RBUniversalSayboltViscosity);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupViscosity1 = new javax.swing.ButtonGroup();
        buttonGroupViscoTypes = new javax.swing.ButtonGroup();
        buttonGroupViscoOil = new javax.swing.ButtonGroup();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        RBSubSatOil = new javax.swing.JRadioButton();
        RBSatuOil = new javax.swing.JRadioButton();
        RBDeadOil = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaViscosity5 = new javax.swing.JTextArea();
        ViscositySat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ImageDeadSat = new javax.swing.JLabel();
        formulas = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaViscosity1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaViscosity3 = new javax.swing.JTextArea();
        ViscosityEffect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaViscosity2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        densityViscoRB = new javax.swing.JRadioButton();
        pressureViscoRB = new javax.swing.JRadioButton();
        tempViscoRB = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaViscosity4 = new javax.swing.JTextArea();
        ViscosityTypes = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        RBApparentViscosity = new javax.swing.JRadioButton();
        RBKinematicViscosity = new javax.swing.JRadioButton();
        RBRelativeViscosity = new javax.swing.JRadioButton();
        RBEnglerViscosity = new javax.swing.JRadioButton();
        RBRedwoodViscosity = new javax.swing.JRadioButton();
        RBFurolSayboltViscosity = new javax.swing.JRadioButton();
        RBUniversalSayboltViscosity = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viscosity");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Crude oil Viscosity"));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        RBSubSatOil.setBackground(new java.awt.Color(255, 255, 255));
        RBSubSatOil.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RBSubSatOil.setText("Sub Saturated Oil Viscosity (uo)");

        RBSatuOil.setBackground(new java.awt.Color(255, 255, 255));
        RBSatuOil.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RBSatuOil.setText("Saturated Oil Viscosity (µob)");

        RBDeadOil.setBackground(new java.awt.Color(255, 255, 255));
        RBDeadOil.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        RBDeadOil.setText("Dead Oil Viscosity (uod)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBSubSatOil)
                    .addComponent(RBSatuOil)
                    .addComponent(RBDeadOil))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBDeadOil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBSatuOil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBSubSatOil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaViscosity5.setEditable(false);
        jTextAreaViscosity5.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaViscosity5.setColumns(20);
        jTextAreaViscosity5.setLineWrap(true);
        jTextAreaViscosity5.setRows(5);
        jTextAreaViscosity5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextAreaViscosity5);

        ViscositySat.setText("Show");
        ViscositySat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViscositySatActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/PVT.jpg"))); // NOI18N

        ImageDeadSat.setBackground(new java.awt.Color(255, 255, 255));

        formulas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ViscositySat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(formulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageDeadSat, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViscositySat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formulas, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImageDeadSat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaViscosity1.setEditable(false);
        jTextAreaViscosity1.setColumns(20);
        jTextAreaViscosity1.setLineWrap(true);
        jTextAreaViscosity1.setRows(5);
        jTextAreaViscosity1.setText("Oil viscosity (µo) is one of the most important physical properties that directly controls and influences fluid flow through porous media and production tubing. Viscosity, in general, is defined as the internal resistance offered by the fluid to flow or movement. In the case of heavy and extra heavy crudes the orders of magnitude can vary from 1000 cps to more than 100,000 cps; from a practical point of view, in order to understand the impact of this variable on fluid mobility we make a comparison with other common substances.");
        jTextAreaViscosity1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaViscosity1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/FluidViscosity.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Viscosity Properties"));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Viscosity Effects"));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaViscosity3.setEditable(false);
        jTextAreaViscosity3.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaViscosity3.setColumns(20);
        jTextAreaViscosity3.setLineWrap(true);
        jTextAreaViscosity3.setRows(5);
        jTextAreaViscosity3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextAreaViscosity3);

        ViscosityEffect.setText("Show");
        ViscosityEffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViscosityEffectActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaViscosity2.setEditable(false);
        jTextAreaViscosity2.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaViscosity2.setColumns(20);
        jTextAreaViscosity2.setLineWrap(true);
        jTextAreaViscosity2.setRows(5);
        jTextAreaViscosity2.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaViscosity2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        densityViscoRB.setBackground(new java.awt.Color(255, 255, 255));
        densityViscoRB.setText("Density on viscosity");

        pressureViscoRB.setBackground(new java.awt.Color(255, 255, 255));
        pressureViscoRB.setText("Pressure on viscosity");

        tempViscoRB.setBackground(new java.awt.Color(255, 255, 255));
        tempViscoRB.setText("Temperature on viscosity");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(densityViscoRB)
                    .addComponent(pressureViscoRB)
                    .addComponent(tempViscoRB)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(densityViscoRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pressureViscoRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempViscoRB))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ViscosityEffect, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViscosityEffect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Viscosity Types"));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaViscosity4.setEditable(false);
        jTextAreaViscosity4.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaViscosity4.setColumns(20);
        jTextAreaViscosity4.setLineWrap(true);
        jTextAreaViscosity4.setRows(5);
        jTextAreaViscosity4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextAreaViscosity4);

        ViscosityTypes.setText("Show");
        ViscosityTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViscosityTypesActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        RBApparentViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBApparentViscosity.setText("Apparent Viscosity");

        RBKinematicViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBKinematicViscosity.setText("Kinematic Viscosity");

        RBRelativeViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBRelativeViscosity.setText("Relative Viscosity");

        RBEnglerViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBEnglerViscosity.setText("Engler Viscosity");

        RBRedwoodViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBRedwoodViscosity.setText("Redwood Viscosity");

        RBFurolSayboltViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBFurolSayboltViscosity.setText("Furol Saybolt Viscosity (SSF)");

        RBUniversalSayboltViscosity.setBackground(new java.awt.Color(255, 255, 255));
        RBUniversalSayboltViscosity.setText("Universal Saybolt Viscosity (SSU)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBApparentViscosity)
                    .addComponent(RBKinematicViscosity)
                    .addComponent(RBRelativeViscosity)
                    .addComponent(RBEnglerViscosity)
                    .addComponent(RBRedwoodViscosity)
                    .addComponent(RBFurolSayboltViscosity)
                    .addComponent(RBUniversalSayboltViscosity))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBApparentViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBKinematicViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBRelativeViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBEnglerViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBRedwoodViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBUniversalSayboltViscosity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBFurolSayboltViscosity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(ViscosityTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViscosityTypes)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViscosityTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViscosityTypesActionPerformed
        if (RBApparentViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoAparente.txt");
            textoViscosity4(is);

        } else if (RBEnglerViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoEngler.txt");
            textoViscosity4(is);

        } else if (RBFurolSayboltViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoSSF.txt");
            textoViscosity4(is);
            
        } else if (RBKinematicViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoCinematica.txt");
            textoViscosity4(is);

        } else if (RBRedwoodViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoRedwood.txt");
            textoViscosity4(is);
            
        } else if (RBRelativeViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoRelativa.txt");
            textoViscosity4(is);

        } else if (RBUniversalSayboltViscosity.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscoSSU.txt");
            textoViscosity4(is);
        } else {
            JOptionPane.showMessageDialog(this, "You must check at least one option.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ViscosityTypesActionPerformed

    private void ViscosityEffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViscosityEffectActionPerformed
        if (pressureViscoRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/EffectivePor.txt");
            textoViscosity3(is);

        } else if (tempViscoRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/IneffectivePor.txt");
            textoViscosity3(is);

        } else if (densityViscoRB.isSelected()) {
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/AbsolutePor.txt");
            textoViscosity3(is);
        } else {
            JOptionPane.showMessageDialog(this, "You must check at least one option.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ViscosityEffectActionPerformed

    private void ViscositySatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViscositySatActionPerformed
        if (RBDeadOil.isSelected()) {
            this.ImageDeadSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Beggs&RobinsonTabla.jpg")));
            this.formulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Beggs&RobinsonFormulas1.jpg")));
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscosityDedOil.txt");
            textoViscosity5(is);

        } else if (RBSatuOil.isSelected()) {
            this.ImageDeadSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Beggs&RobinsonTabla.jpg")));
            this.formulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Beggs&RobinsonFormulas2.jpg")));
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscositySatOil.txt");
            textoViscosity5(is);

        } else if (RBSubSatOil.isSelected()) {
            this.ImageDeadSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Vazquez&BeggsTabla.jpg")));
            this.formulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/formulas/Viscosity/Beggs&RobinsonFormulas3.jpg")));
            InputStream is = getClass().getResourceAsStream("/Textos/PorVisCapiGOR/Viscosity/ViscositySubSatOil.txt");
            textoViscosity5(is);
        } else {
            JOptionPane.showMessageDialog(this, "You must check at least one option.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ViscositySatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viscosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viscosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viscosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viscosity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Viscosity dialog = new Viscosity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void textoViscosity2(InputStream is) {
        jTextAreaViscosity2.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaViscosity2.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void textoViscosity3(InputStream is) {
        jTextAreaViscosity3.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaViscosity3.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void textoViscosity4(InputStream is) {
        jTextAreaViscosity4.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaViscosity4.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void textoViscosity5(InputStream is) {
        jTextAreaViscosity5.setText("");
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(is));
            String linea = read.readLine();
            while (linea != null) {
                jTextAreaViscosity5.append(linea + "\n");
                linea = read.readLine();
            }
        } catch (Exception ex) {
            Logger.getLogger(Porosity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void pintarImagen(JLabel lbl, String ruta) {
        lbl.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(ruta)).getImage().getScaledInstance(
                lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageDeadSat;
    private javax.swing.JRadioButton RBApparentViscosity;
    private javax.swing.JRadioButton RBDeadOil;
    private javax.swing.JRadioButton RBEnglerViscosity;
    private javax.swing.JRadioButton RBFurolSayboltViscosity;
    private javax.swing.JRadioButton RBKinematicViscosity;
    private javax.swing.JRadioButton RBRedwoodViscosity;
    private javax.swing.JRadioButton RBRelativeViscosity;
    private javax.swing.JRadioButton RBSatuOil;
    private javax.swing.JRadioButton RBSubSatOil;
    private javax.swing.JRadioButton RBUniversalSayboltViscosity;
    private javax.swing.JButton ViscosityEffect;
    private javax.swing.JButton ViscositySat;
    private javax.swing.JButton ViscosityTypes;
    private javax.swing.ButtonGroup buttonGroupViscoOil;
    private javax.swing.ButtonGroup buttonGroupViscoTypes;
    private javax.swing.ButtonGroup buttonGroupViscosity1;
    private javax.swing.JRadioButton densityViscoRB;
    private javax.swing.JLabel formulas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaViscosity1;
    private javax.swing.JTextArea jTextAreaViscosity2;
    private javax.swing.JTextArea jTextAreaViscosity3;
    private javax.swing.JTextArea jTextAreaViscosity4;
    private javax.swing.JTextArea jTextAreaViscosity5;
    private javax.swing.JRadioButton pressureViscoRB;
    private javax.swing.JRadioButton tempViscoRB;
    // End of variables declaration//GEN-END:variables
}
